#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define SERVO_FREQ 50
#define SERVO_COUNT 15

#define LEDS_DATA_PIN D3
#define COLOR_ORDER GRB
#define BRIGHTNESS 255
#define FRAMES_PER_SECOND 120
#define LED_TYPE WS2812B

#endif